FROM debian:stable-slim

RUN apt-get update \
 && apt-get install -y python3 python3-paho-mqtt \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /client

COPY certs /client/certs
COPY main.py .

CMD ["python3", "main.py"]
