FROM docker.io/library/debian:stable-slim

RUN apt-get update \
 && apt-get install -y python3 python3-paho-mqtt \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /client

COPY certs /client/certs
COPY entrypoint.sh .
COPY main.py .

RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]
