version: "3.9"

services:
  ble:
    build: ble_engine
    container_name: ble
    privileged: true
    volumes:
      - /run/dbus:/run/dbus:rw,Z
  mosquitto:
    build: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    environment:
      TZ: Europe/Vienna
    ports:
      - "8883:8883"
    volumes:
      - ./iot_storage/mosquitto-data-storage:/mosquitto/data:Z
      - ./iot_storage/mosquitto-log-storage:/mosquitto/log:Z
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z

  client:
    build: client
    CONainer_name: client
    restart: unless-stopped
    depends_on:
      mosquitto:
        condition: service_healthy
