version: "3"

services:

  ble:
    build: ble_engine
    volumes:
      - /run/dbus:/run/dbus:rw,z
    network_mode: host
    privileged: true

  mosquitto:
    build: mosquitto
    restart: unless-stopped
    environment:
      TZ: Europe/Vienna
    ports:
      - "8883:8883"
    volumes:
      - /home/mosud/iot_storage/mosquitto-data-storage:/mosquitto/data
      - /home/mosud/iot_storage/mosquitto-log-storage:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z

  client:
    build: client
    restart: unless-stopped
    depends_on:
      - mosquitto
