#Containerfile

FROM debian:latest

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3 python3-pydbus bluez

COPY modules ./modules
COPY entrypoint.sh .
COPY main.py .
#COPY main_updated.py .
RUN chmod a+x entrypoint.sh

# Upgrade pip and install numpy
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir numpy


CMD ["./entrypoint.sh"]
