#Containerfile

FROM debian:latest

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3 python3-pydbus python3-paho-mqtt bluez

COPY modules ./modules
COPY certs/* /ble_certs/certs/
RUN  ls -l /ble_certs/certs/
RUN sleep 5
COPY artifacts.py .
COPY entrypoint.sh .
COPY main.py .
#COPY main_updated.py .
RUN chmod a+x entrypoint.sh



CMD ["./entrypoint.sh"]
